---
title: "ancestral_state_reconstruction_cluster_detection"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ancestral_state_reconstruction_cluster_detection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(phylosuite)
library(tidyverse)
library(ape)
library(ggtree)
```

# Load test data
## Dataframe
1. tip_name_var = variable with tip names
2. Patient_ID = Patient_IDs
3. clades = what clade the isolate belongs to
4. colistin_ns = colistin non-susceptibility. 1 = non-susceptible. 0 = susceptible
```{r}
df <- phylosuite::df  
paste0("Total of 413 isolates")
paste0("Number of patients: ",length(unique(df$Patient_ID)))
dim(df)
paste0("First few isolates")
head(df)
paste0("Frequency of non-susceptibility to colistin: ")
table(df$colistin_ns)
```
## Tree
```{r,fig.width=7.5,fig.height=7.5}
tr <- phylosuite::tr
ggtree(tr)
p0 <- gheatmap(ggtree(tr),df %>% select(colistin_ns) %>% mutate_all(as.factor),colnames_position = 'top',width = .25,low = 'white',high='black',colnames_angle = 90,legend_title = 'Colistin non-usceptibility',hjust = 0,color = NULL) + ylim(NA,485)
```

# Step 1: Run ancestral state reconstruction 
```{r}
asr_obj <- phylosuite::asr(df,tr,"tip_name_var","colistin_ns","ER","joint")

paste0("Output names: ")
names(asr_obj)

paste0("corHMM_out: the corHMM output")
asr_obj$corHMM_out

paste0("corHMM_model_summary: A summary of the corHMM model, including the number of parameters, model, number of rate categories, rates, log likelihood, AIC, and AICc")
asr_obj$corHMM_model_summary

paste0("node_states: Chosen node state that was modeled")
asr_obj$node_states

paste0("parent_child_df: Parent child dataframe, which contains the edge dataset, parent and child values, the child name (for tips), and transition data (i.e., gain, loss, and continuation)")
head(asr_obj$parent_child_df)
```

# Step 2: Cluster detection
```{r,fig.width=7.5,fig.height=7.5}
asr_cluster_obj <- asr_cluster_detection(df = df,tr=tr,tip_name_var = "tip_name_var",patient_id = 'PatientID',pheno = 'colistin_ns',parent_child_df = asr_obj$parent_child_df,node_states = 'joint',confidence = NULL,faux_clusters = 'remove',remove_revertant = 'yes',collapse_cluster = 'yes')

paste0("Cluster detection dataframe")
colnames(asr_cluster_obj)
head(asr_cluster_obj)

paste0("asr_cluster: raw clustering data")
table(asr_cluster_obj$asr_cluster)

paste0("asr_cluster_renamed: Renamed a singleton, cluster, and no feature")
table(asr_cluster_obj$asr_cluster_renamed)

paste0("asr_cluster_collapsed: Collapsed as singleton, cluster, or no feature")
table(asr_cluster_obj$asr_cluster_collapsed)

paste0("Cluster on tree")
p0.1 <- p0+ggnewscale::new_scale_fill()
gheatmap(p0.1,asr_cluster_obj %>% select(asr_cluster_renamed) %>% mutate_all(as.factor),colnames_position = 'top',width = .25,low = 'white',high='black',colnames_angle = 90,legend_title = 'Colistin non-usceptibility',hjust = 0,offset=0.0000075,color=NULL) + ylim(NA,625)
```
# Step 3: Cluster statistics
```{r,fig.width=7.5,fig.height=7.5}
asr_cluster_analysis(asr_cluster_obj,remove_faux = 'yes')
```


