#' nearest_neighbor_summary_statistics: Generate summary statistics of nearest neighbor comparisons for isolate pairs
#'
#' This function will generate summary statistics for nearest neighbor comparisons generated by phyloAMR::nearest_neighbor_analysis()
#'
#' @param nearest_neighbor_differences Dataframe with isolates and their nearest neighbors, generated from nearest_neighbor_analysis.
#' @param categorical_vars Categorical variables. Must be in the comparison_df
#' @param binary_vars Binary variables. Must be in the comparison_df AND coded 0 and 1.
#' @param continuous_vars Continuous variables. Must be in the comparison_df
#' @param continuous_vars Continuous variables. Must be in the comparison_df
#' @param log_2 Boolean (TRUE/FALSE) Whether to perform log-2 transformation on continuous variables
#' @return Dataframe with differences in the categorical and continuous variables between an isolate and their nearest neighbor
#' @export

nearest_neighbor_summary_statistics <- function(nearest_neighbor_differences, categorical_vars = NULL, binary_vars = NULL, continuous_vars = NULL, log_2 = FALSE) {
  # Create summary dataset
  comps_sum <- cbind.data.frame(comparison_feature = unique(nearest_neighbor_differences[["comparison_feature"]]),
                                n = nrow(nearest_neighbor_differences))

  # Categorical differences
  if (is.null(categorical_vars) == FALSE) {
    continuous_vars_names <- paste0(categorical_vars, "_categorical_diff")
    cat_sum_df <- lapply(continuous_vars_names, FUN = function(x) {
      cat_summary(x, nearest_neighbor_differences = nearest_neighbor_differences, n =  comps_sum[["n"]])
    })
    cat_sum_df <- do.call(cbind.data.frame, cat_sum_df)
    comps_sum <- cbind(comps_sum, cat_sum_df)
  }

  # Binary differences
  if (is.null(binary_vars) == FALSE) {
    binary_vars_names <- paste0(binary_vars, "_binary_diff")
    binary_sum_df <- lapply(binary_vars_names, FUN = function(x) {
      binary_summary(x, nearest_neighbor_differences = nearest_neighbor_differences, n = comps_sum[["n"]])
    })
    binary_sum_df <- do.call(cbind.data.frame, binary_sum_df)
    comps_sum <- cbind(comps_sum, binary_sum_df)
  }

  # Continuous
  if (is.null(continuous_vars) == FALSE) {
    if (log_2 == TRUE) {
      continuous_vars_names <- c(paste0(continuous_vars, "_diff"), paste0(continuous_vars, "_log_2_diff"))
      cont_sum_df <- lapply(continuous_vars_names, FUN = function(x) {
        cont_summary(x, nearest_neighbor_differences = nearest_neighbor_differences, n = comps_sum[["n"]])
      })
      cont_sum_df <- do.call(cbind.data.frame, cont_sum_df)
    } else {
      continuous_vars_names <- c(paste0(continuous_vars, "_diff"))
      cont_sum_df <- lapply(continuous_vars_names, FUN = function(x) {
        cont_summary(x, nearest_neighbor_differences = nearest_neighbor_differences, n = comps_sum[["n"]])
      })
      cont_sum_df <- do.call(cbind.data.frame, cont_sum_df)
  }
    comps_sum <- cbind(comps_sum, cont_sum_df)
  }

  return(comps_sum)
}

# Generate summary statistics for categorical data
cat_summary <- function(var, nearest_neighbor_differences, n) {
  difference_prop <- sum(nearest_neighbor_differences[, var] != "same") / n
  data <- cbind.data.frame(difference_prop)
  colnames(data) <- paste0(var,  c("_difference_prop"))
  return(data)
}

# Generate summary statistics for binary data
binary_summary <- function(var, nearest_neighbor_differences, n) {
  gain_prop <- sum(nearest_neighbor_differences[, var] == "gain") / n
  loss_prop <- sum(nearest_neighbor_differences[, var] == "loss") / n
  data <- cbind.data.frame(gain_prop, loss_prop)
  colnames(data) <- paste0(var,  c("_gain_prop", "_loss_prop"))
  return(data)
}

# Generate summary statistics for continuous data
cont_summary <- function(var, nearest_neighbor_differences, n) {
  string <- nearest_neighbor_differences[[var]]
  median <- stats::median(string)
  mean <- mean(string)
  range <- paste0(range(string), collapse = "-")
  increase_prop <- sum(string > 0) / n
  decrease_prop <- sum(string < 0) / n
  data <- cbind.data.frame(median, mean, range, increase_prop, decrease_prop)
  colnames(data) <- paste0(var, "_", colnames(data))
  return(data)
}
